export const INPUT_NUMBER_PATTERN_WITH_2_CHARS = "\d+{2}";
export const TYPE_TEXT = "text";
export const TYPE_NUMBER = "number"
export const PATH_TO_HOME = "/"
export const BACK_LABEL_VALUE = "Back";
export const SAVE_BUTTON_TEXT = "Save";
export const RESET_BUTTON_TEXT = "Reset";
export const SETTINGS_TITLE = "SETTINGS";
export const POMO_TITLE = "POMO";
export const LONG_REST_BUTTON_TEXT = "Long Rest";
export const SHORT_REST_BUTTON_TEXT = "Short Rest";
export const SIZE_ICON_2X = "2x";
export const SETTINGS_LABEL = "Settings";
export const PATH_TO_SETTINGS = "/settings";
export const FIVE_SECONDS_IN_MS = 5000;
export const UNIT_30_PX = "30px";
export const LABEL_MINUTES_FOR_SHORT_REST = "MINUTES FOR SHORT REST";
export const LABEL_MINUTES_FOR_LONG_REST = "MINUTES FOR SHORT REST";
export const LABEL_MINUTES_FOR_TO_FOCUS = "MINUTES FOR TO FOCUS";
export const MAX_LENGTH_60 = 60;
export const MIN_LENGTH_20 = 20;
export const MIN_LENGTH_15 = 15;
export const MIN_LENGTH_5 = 5;